spring.config.import=optional:file:.env[.properties]

spring.application.name=backend

server.address=0.0.0.0
#server.port=${PORT:10000}
server.port=${PORT:8080}

spring.mongodb.uri=${MONGODB_URI}
spring.mongodb.database=devmind
spring.data.mongodb.auto-index-creation=true